### ISSUE TITLE
code availability

### ISSUE THREAD

**Issue by juliangaal** [thkreutz/umosmots#1]
Your paper looks fantastic! Any idea when your code will be available?

**Comment by thkreutz** [comment]
Hey, thank you for your interest in this work. Unfortunately, I have been quite busy the last few months. I will upload my code in the coming weeks!

**Comment by thkreutz** [comment]
Update: Refactored+documented code for ease-of-use, running last tests to make sure everything works smoothly. code+data will appear in this repo latest by the end of this week.
